name: firebase_functions_interop
description: Firebase Cloud Functions SDK for Dart written as a JS interop wrapper for official Node.js SDK.
version: 1.0.2
homepage: https://www.github.com/pulyaevskiy/firebase-functions-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  js: ^0.6.1+1
  meta: ^1.1.7
  node_interop: ^1.0.3
  node_io: ^1.0.1+2
  node_http: ^1.0.0
  firebase_admin_interop:
    git:
      url: https://github.com/Skquark/firebase-admin-interop

dev_dependencies:
  test: any
